<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "twtdh_inetauth"
 *
 * Auto generated by Extension Builder 2018-08-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => 'Internet Authentification',
    'description' => 'Instead of fe login and fe access rights an authentification via internet replaces it - also acces rights for pages',
    'category' => 'services',
    'author' => '',
    'author_email' => '',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => array(
        'depends' => array(
            'typo3' => '8.7.0-8.7.99',
        ),
        'conflicts' => array(),
        'suggests' => array(),
    ),
  'autoload' =>
    array(
      'psr-4' => array('Twtdh\\TwtdhInetauth\\' => 'Classes')
    ),

);
